name: efrei_todo
description: Todo app collab-ready
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  go_router: ^14.2.3
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true
